# The Axiom of Extension

A pack of wolves, a bunch of grapes, or a flock of pigeons are all examples of sets of things. The mathematical concept of a set can be used as the foundation for all known mathematics. The purpose of this little book is to develop the basic properties of sets. Incidentally, to avoid terminological monotony, we shall sometimes say `\textit{collection}\index{collection}`{=latex} `<em>collection</em>`{=html} instead of `\textit{set}\index{set}`{=latex} `<em>set</em>`{=html}. The word "class"`\index{class}`{=latex} is also used in this context, but there is a slight danger in doing so. The reason is that in some approaches to set theory "class" has a special technical meaning. We shall have occasion to refer to this again a little later.

One thing that the development will not include is a definition of sets. The situation is analogous to the familiar axiomatic approach to elementary geometry. That approach does not offer a definition of points and lines; instead it describes what it is that one can do with those objects. The semi-axiomatic point of view adopted here assumes that the reader has the ordinary, human, intuitive (and frequently erroneous) understanding of what sets are; the purpose of the exposition is to delineate some of the many things that one can correctly do with them.

Sets, as they are usually conceived, have `\textit{elements}\index{element}`{=latex} `<em>elements</em>`{=html} or `\textit{members}\index{member}`{=latex} `<em>members</em>`{=html}. An element of a set may be a wolf, a grape, or a pigeon. It is important to know that a set itself may also be an element of some other set. Mathematics is full of examples of sets of sets. A line, for instance; is a set of points; the set of all lines in the plane is a natural example of a set of sets (of points). What may be surprising is not so much that sets may occur as elements, but that for mathematical purposes no other elements need ever be considered. In this book, in particular, we shall study set, and sets of sets, and similar towers of sometimes frightening height and complexity — and nothing else. By way of examples we might occasionally speak of sets of cabbages, and kings, and the like, but such usage is always to be construed as an illuminating parable only, and not as a part of the theory that is being developed. 

The principal concept of set thoery, the one that in completely axiomatic studies is the principal primitive (undefined) concept, is that of `\textit{belonging}\index{belonging}`{=latex} `<em>belonging</em>`{=html}. If $x$ belongs to $A$ ($x$ is an element of $A$, $x$ is `\textit{contained}\index{contain}`{=latex} `<em>contained</em>`{=html} in $A$), we shall write 

$$
x \in A.
$$

This version of the Greek letter epsilon is so often used to denote belonging that its use to denote anything else is almost prohibited. Most authors relegate $\in$ to its set-theoretic use forever and use $\varepsilon$ when they need the fifth letter of the Greek alphabet. 

Perhaps a brief digression on alphabetic etiquette in set theory might be helpful. There is no compelling reason for using small and capital letters as in the preceding paragraph; we might have written, and often will write, things like $x \in y$ and $A \in B$. Whenever possible, however, we shall informally indicate the status of a set in a particular hierarchy under consideration by means of the convention that letters at the beginning of the alphabet denote elements, and letters at the end denote sets containing them; similarly letters of a relatively simple kind denote elements, and letters of the larger and gaudier fonts denote sets containing them. Examples: $x \in A$, $A \in X$, $X \in \mathcal{C}$.


A possible relation between sets, more elementary than belonging, is `\textit{equality}\index{equality}`{=latex} `<em>equality</em>`{=html}. The equality of two sets $A$ and $B$ is universally denoted by the familiar symbol 

$$
A = B;
$$

the fact that $A$ and $B$ are not equal is expressed by writing 

$$
A \neq B.
$$

The most basic property of belonging is its relation to equality, which can be formulated as follows.