# Preface by the Editors {.unnumbered}

As the book title says, this is the famous set theory book *Naive Set Theory* by Paul Richard Halmos, first published in 1960 by D. Van Nostrand Company, INC., part of a series called *The University Series in Undergraduate Mathematics*.

What the title doesn't say is that this version is an independent re-edition. The original work is currently public domain in [Hathi Trust Digital Library](https://babel.hathitrust.org) — the reader probably found (or could find) the original digitized book on Google by just searching for its title. This version was written in LaTeX and first released on July 14, 2023, available for free download on my [Github repository](https://github.com/matheusgirola/Halmos-Naive-Set-Theory-OCR-LaTeX-Reedition). After the initial release, some people have already made contributions in fixing typos and further improving the re-edition. I extend here my gratitude to these people for helping me and keeping the spirit of the re-edition alive.

Even though the book was freely available online, there are three reasons for this project. First, the book in its digitized state is perfectly readable, but it doesn't allow searching words with {{< kbd mac=Command-F win=Ctrl-F linux=Ctrl-F >}} and doesn't have an interactive summary with it. The second is to update the book by correcting the errors in the original version, following the published [errata](https://en.wikipedia.org/wiki/Naive_Set_Theory_(book)#Errata) - as noticed, and updated in this edition, by Michał Zdunek. The third reason is purely personal, I have a passion and gratitude for this book and, while I want to learn OCR, I decided to re-edit it as a homage.

Some notes on this re-edition are necessary. The book page format is B5 paper with font size 12pt. The margins of the book should be perfectly suitable for printing. The main differences with the original editions are the cover and the chapter title page designs. The mathematical symbol which denotes *set inclusion* in the original is ($\epsilon$), but I opted to use ($\in$) since it's used regularly nowadays for this case. Besides this, I didn't change anything in the text. Therefore, any mistakes — which I hope are non-existent or, at least, few — are solely mine, and if someone finds any, please contact me via [e-mail](mailto:matheusgirola@gmail.com).

As mentioned, the original book is in the public domain and, so, freely available on the internet. Therefore, the resulting re-edition of the book at the end of this project has no lucrative ends by any means. This re-edition cannot be used for any commercial purposes.

I thought about writing a short story about Paul R. Halmos, since it's common for books to do this, especially after the author has deceased. However, I couldn't do a better job than someone just searching on Google and/or Wikipedia. So, for now, I will just say that this book has a special place in my heart. It was one of the first works that introduced and helped me push through writing proofs. And at the end, I fell in love not only with it, but with mathematics overall. I hope that anybody who found this version can have the same outcome as I did. Now read it, absorb it, and forget it.

<!--
Check
https://github.com/orgs/quarto-dev/discussions/13178
https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html#block-syntax
-->

::: {.flushright latex=""}
Matheus Girola Macedo Barbosa - 2024-07-01
:::

This book is a modernized re-edition of Paul R. Halmos’s classic Naive Set Theory, authored using [Quarto](https://quarto.org/) and based on the LaTeX source and OCR work by [Matheus Girola Macedo Barbosa](https://github.com/matheusgirola/Halmos-Naive-Set-Theory-OCR-LaTeX-Reedition). This version is available for free download on my [Github repository](https://github.com/luifrancgom/halmos_naive_set_theory_quarto) repository and is licensed under the [CC BY-NC-SA 4.0]( https://creativecommons.org/licenses/by-nc-sa/4.0/). The cover features a detail from [The Garden of Earthly Delights](https://en.wikipedia.org/wiki/The_Garden_of_Earthly_Delights) by Hieronymus Bosch (circa 1450–1516), a public domain work chosen to reflect the intricate and foundational nature of the set-theoretic universe.

<!--
Check
https://github.com/orgs/quarto-dev/discussions/13178
https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html#block-syntax
-->

::: {.flushright latex=""}
Luis Francisco Gomez Lopez - 2025-12-31
:::